services:
  msceqf:
    image: msceqf:ros${ROS_VERSION:-1}
    network_mode: host
    stdin_open: true
    tty: true
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=all
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all # from --gpus all
              capabilities: [gpu]
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /home/${USER}/Projects/datasets:/root/datasets
      - /home/${USER}/Projects/params:/root/params
      - /home/${USER}/.tmux.conf:/root/.tmux.conf:ro
