FROM osrf/ros:noetic-desktop-full

# Install dependencies
RUN apt-get update && apt-get install -y \
    vim-gtk3\
    nano \
    tmux \
    git \
    python3-catkin-tools \
    python3-osrf-pycommon \
    python3-wstool \
    build-essential

# Set up the catkin workspace
RUN mkdir -p /root/catkin_ws/src/msceqf
COPY . /root/catkin_ws/src/msceqf/

# Set the working directory for the build
WORKDIR /root/catkin_ws

# Source the ROS environment and build the workspace in a single RUN layer.
RUN . /opt/ros/noetic/setup.sh && \
    catkin build -DCMAKE_BUILD_TYPE=${BUILD_TYPE:-Release} -DROS_BUILD=ON

# Add the workspace setup to .bashrc for interactive shells
RUN echo "source /opt/ros/noetic/setup.bash" >> /root/.bashrc && \
    echo "source /root/catkin_ws/devel/setup.bash" >> /root/.bashrc

# Set the final working directory
WORKDIR /root
